Imports System

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace m0c_dpi_killer


	''' <summary>
	'''   A strongly-typed resource class, for looking up localized strings, etc.
	''' </summary>
	' This class was auto-generated by the StronglyTypedResourceBuilder
	' class via a tool like ResGen or Visual Studio.
	' To add or remove a member, edit your .ResX file then rerun ResGen
	' with the /str option, or rebuild your VS project.
	<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()> _
	Friend Class Resource1

		Private Shared resourceMan As Global.System.Resources.ResourceManager

		Private Shared resourceCulture As Global.System.Globalization.CultureInfo

		<Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")> _
		Friend Sub New()
		End Sub

		''' <summary>
		'''   Returns the cached ResourceManager instance used by this class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As New Global.System.Resources.ResourceManager("Resource1", GetType(Resource1).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		''' <summary>
		'''   Overrides the current thread's CurrentUICulture property for all
		'''   resource lookups using this strongly typed resource class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set(ByVal value As System.Globalization.CultureInfo)
				resourceCulture = value
			End Set
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Byte[].
		''' </summary>
		Friend Shared ReadOnly Property _32_goodbyedpi() As Byte()
			Get
				Dim obj As Object = ResourceManager.GetObject("_32_goodbyedpi", resourceCulture)
				Return (DirectCast(obj, Byte()))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Byte[].
		''' </summary>
		Friend Shared ReadOnly Property _32_WinDivert_dll() As Byte()
			Get
				Dim obj As Object = ResourceManager.GetObject("_32_WinDivert_dll", resourceCulture)
				Return (DirectCast(obj, Byte()))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Byte[].
		''' </summary>
		Friend Shared ReadOnly Property _32_WinDivert32_sys() As Byte()
			Get
				Dim obj As Object = ResourceManager.GetObject("_32_WinDivert32_sys", resourceCulture)
				Return (DirectCast(obj, Byte()))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Byte[].
		''' </summary>
		Friend Shared ReadOnly Property _64_goodbyedpi() As Byte()
			Get
				Dim obj As Object = ResourceManager.GetObject("_64_goodbyedpi", resourceCulture)
				Return (DirectCast(obj, Byte()))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Byte[].
		''' </summary>
		Friend Shared ReadOnly Property _64_WinDivert_dll() As Byte()
			Get
				Dim obj As Object = ResourceManager.GetObject("_64_WinDivert_dll", resourceCulture)
				Return (DirectCast(obj, Byte()))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Byte[].
		''' </summary>
		Friend Shared ReadOnly Property _64_WinDivert64_sys() As Byte()
			Get
				Dim obj As Object = ResourceManager.GetObject("_64_WinDivert64_sys", resourceCulture)
				Return (DirectCast(obj, Byte()))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Byte[].
		''' </summary>
		Friend Shared ReadOnly Property dnscrypt_proxy() As Byte()
			Get
				Dim obj As Object = ResourceManager.GetObject("dnscrypt_proxy", resourceCulture)
				Return (DirectCast(obj, Byte()))
			End Get
		End Property
	End Class
End Namespace
